name: 'PR AGENT Analysis'

on:
  pull_request:
    types: [opened, reopened] # Trigger when a PR is opened or reopened

jobs:
  analyze:
    runs-on: ubuntu-latest
    # Define the minimum permissions required for this job
    permissions:
      pull-requests: write # Required to post comments
      contents: read       # Required to checkout the code

    steps:
      # Step 1: Get the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install our application's dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the core application logic
      - name: Run PR AGENT
        env:
          # Securely pass secrets and context to our Python script
          KRITIK_APP_ID: ${{ secrets.PR_AGENT_APP_ID }}
          KRITIK_PRIVATE_KEY: ${{ secrets.PR_AGENT_PRIVATE_KEY }}
          GITHUB_CONTEXT: ${{ toJSON(github) }} # Pass the entire event payload
        run: python src/main.py