name: 'PR_AGENT Analysis'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run PR_AGENT Analysis
        env:
          PR_AGENT_APP_ID: ${{ secrets.PR_AGENT_APP_ID }}
          PR_AGENT_PRIVATE_KEY: ${{ secrets.PR_AGENT_PRIVATE_KEY }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: python src/main.py